# Generated by Django 5.1.2 on 2024-10-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('context_construct', models.JSONField(blank=True)),
                ('id_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.folder')),
            ],
        ),
    ]
