# Generated by Django 5.1.2 on 2024-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='context_construct',
            new_name='content_construct',
        ),
        migrations.AddField(
            model_name='file',
            name='content_origin',
            field=models.TextField(blank=True),
        ),
    ]
