# Generated by Django 5.1.2 on 2024-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_context_construct_file_content_construct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content_origin',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_construct',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
