# Generated by Django 5.1.2 on 2024-10-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
