# Generated by Django 5.1.2 on 2024-10-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='src',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
