# Generated by Django 5.1.2 on 2024-10-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_file_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.folder'),
        ),
    ]
