# Generated by Django 5.1.2 on 2024-10-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_folder_id_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content_construct',
            new_name='content_cypher',
        ),
    ]
